Run `trustfall_stubgen` tests when the directory has changed.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -179,7 +179,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
         with:
-          persist-credentials: false
+          persist-credentials: true
 
       - name: Install rust
         uses: dtolnay/rust-toolchain@stable
@@ -189,9 +189,16 @@ jobs:
       - uses: r7kamura/rust-problem-matchers@v1
 
       # Test everything except trustfall_stubgen,
-      # which is only tested at release time since its tests are a bit long.
+      # which is only tested if it has changed since its tests are a bit long.
       - name: cargo test
         run: cargo test --workspace --all-targets --all-features --exclude trustfall_stubgen
+
+      - name: test trustfall_stubgen if it has changed
+        run: |
+          git fetch origin main
+
+          # `git diff --quiet` exits non-zero if there are changes
+          git diff --quiet HEAD origin/main -- ./trustfall_stubgen || (cd trustfall_stubgen/ && cargo test --all-targets --all-features)
 
   rust-fuzz:
     name: Check fuzz targets
